# Generated by Django 4.2.4 on 2023-09-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createauction',
            name='auction_status',
            field=models.CharField(max_length=15),
        ),
    ]
