# Generated by Django 4.2.4 on 2023-09-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='addVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_name', models.CharField(max_length=30)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('manager', models.CharField(max_length=30)),
            ],
        ),
    ]
