# Generated by Django 4.2.4 on 2023-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_addvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
