# Generated by Django 4.2.4 on 2023-09-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='userFeedback',
        ),
    ]
