# Generated by Django 4.2.4 on 2023-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_addvehicle_minimum_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvehicle',
            name='bid_end_date',
            field=models.DateField(default='0-0-0'),
        ),
        migrations.AddField(
            model_name='addvehicle',
            name='bid_status',
            field=models.CharField(default='open', max_length=30),
        ),
    ]
