# Generated by Django 4.2.4 on 2023-09-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_addvehicle_bid_end_date_addvehicle_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvehicle',
            name='bid_end_date',
            field=models.DateField(default='2018-05-06'),
        ),
    ]
