# Generated by Django 4.2.4 on 2023-09-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_addvehicle_bid_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvehicle',
            name='bid_end_date',
        ),
    ]
