# Generated by Django 4.2.4 on 2023-09-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_addvehicle_bid_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvehicle',
            old_name='bid_end_date',
            new_name='bid_end_day',
        ),
    ]
