# Generated by Django 4.2.4 on 2023-09-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_remove_addvehicle_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvehicle',
            name='bid_end_date',
            field=models.CharField(default='notspecified', max_length=50),
        ),
        migrations.AddField(
            model_name='addvehicle',
            name='bid_status',
            field=models.CharField(default='open', max_length=30),
        ),
    ]
