myApp.config(['$urlRouterProvider', '$stateProvider', function($urlRouterProvider, $stateProvider){
    $stateProvider
    .state('addDepartment',{
        url:'/addDepartment',
        templateUrl:'./addDepartment.html',
        controller:'addDepartmentController'
    })
    .state('removeDepartment',{
        url:'/removeDepartment',
        templateUrl:'./removeDepartment.html',
        controller:'removeDepartmentController'
    })
    .state('departmentDetails',{
        url:'/departmentDetails',
        templateUrl:'./departmentDetails.html',
        controller:'departmentDetailsController'
    })
    .state('addDesignation',{
        url:'/addDesignation',
        templateUrl:'./addDesignation.html',
        controller:'addDesignationController'
    })
    .state('removeDesignation',{
        url:"/removeDesignation",
        templateUrl:'./removeDesignation.html',
        controller:'removeDesignationController'
    })
    .state('addEmployee',{
        url:"/addEmployee",
        templateUrl:'./addEmployee.html',
        controller:'addEmployeeController'
    })
    .state('removeEmployee',{
        url:'/removeEmployee',
        templateUrl:'./removeEmployee.html',
        controller:'removeEmployeeController'
    })
    .state('updateSalary',{
        url:"/updateSalary",
        templateUrl:'./updateSalary.html',
        controller:'updateSalaryController'
    })
    .state('salaryDetails',{
        url:"/salaryDetails",
        templateUrl:'./salaryDetails.html',
        controller:'salaryDetailsController'
    })
    .state('addProject',{
        url:"/addProject",
        templateUrl:'./addProject.html',
        controller:'addProjectController'
    })
    .state('removeProject',{
        url:"/removeProject",
        templateUrl:'./removeProject.html',
        controller:'removeProjectController'
    })
    .state('generatePayslip',{
        url:"/generatePayslip",
        templateUrl:'./generatePayslip.html',
        controller:'payslipController'
    })
    .state('printPayslip',{
        url:"/printPayslip",
        templateUrl:'./printPayslip.html',
        controller:'payslipController'
    })

    $urlRouterProvider.otherwise('addDepartment');
    ;
}]);
